# Generated by Django 3.1.7 on 2021-06-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artabloom', '0002_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
