# Generated by Django 3.1.7 on 2021-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artabloom', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
